// <auto-generated />
using System;
using DataLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataLayer.Migrations
{
    [DbContext(typeof(AmlakDbContext))]
    [Migration("20200915040940_adddescriptiontocontract")]
    partial class adddescriptiontocontract
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainLayer.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<int>("AdminType");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("DomainLayer.Adviser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("BackgroundImage")
                        .HasMaxLength(500);

                    b.Property<string>("BuyTakhasos");

                    b.Property<bool>("CanAdd");

                    b.Property<int?>("CityId");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("Email");

                    b.Property<int>("ExperienceYear");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Image")
                        .HasMaxLength(500);

                    b.Property<string>("Manategh");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("RentTakhasos");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("Adviser");
                });

            modelBuilder.Entity("DomainLayer.AmlakDivar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakDivar");
                });

            modelBuilder.Entity("DomainLayer.AmlakEmtiaz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakEmtiaz");
                });

            modelBuilder.Entity("DomainLayer.AmlakEskeleton", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakEskeleton");
                });

            modelBuilder.Entity("DomainLayer.AmlakJahatVahed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakJahatVahed");
                });

            modelBuilder.Entity("DomainLayer.AmlakKaf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakKaf");
                });

            modelBuilder.Entity("DomainLayer.AmlakKitchen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakKitchen");
                });

            modelBuilder.Entity("DomainLayer.AmlakMelkStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakMelkStatus");
                });

            modelBuilder.Entity("DomainLayer.AmlakMogheiatMelk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakMogheiatMelk");
                });

            modelBuilder.Entity("DomainLayer.AmlakMoshaat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakMoshaat");
                });

            modelBuilder.Entity("DomainLayer.AmlakMoshakhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakMoshakhase");
                });

            modelBuilder.Entity("DomainLayer.AmlakNema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakNema");
                });

            modelBuilder.Entity("DomainLayer.AmlakNoeZamin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakNoeZamin");
                });

            modelBuilder.Entity("DomainLayer.AmlakParking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakParking");
                });

            modelBuilder.Entity("DomainLayer.AmlakPishraftStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakPishraftStatus");
                });

            modelBuilder.Entity("DomainLayer.AmlakSaghf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakSaghf");
                });

            modelBuilder.Entity("DomainLayer.AmlakSanadStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakSanadStatus");
                });

            modelBuilder.Entity("DomainLayer.AmlakTasisatGarmaieshi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakTasisatGarmaieshi");
                });

            modelBuilder.Entity("DomainLayer.AmlakWC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name");

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("AmlakWC");
                });

            modelBuilder.Entity("DomainLayer.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityPhoneCode");

                    b.Property<string>("Code");

                    b.Property<string>("Gpsx")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Gpsy")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("RegionId");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("City");
                });

            modelBuilder.Entity("DomainLayer.Contract.Contract", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AdviserId");

                    b.Property<long>("BuyCost");

                    b.Property<int?>("CostumerId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<long?>("FinalCost1");

                    b.Property<long?>("FinalCost2");

                    b.Property<long?>("FinalCost3");

                    b.Property<string>("GharardadNumber");

                    b.Property<int>("HomeId");

                    b.Property<int>("Metraz");

                    b.Property<int>("MetrazZamin");

                    b.Property<long>("RentCOst");

                    b.Property<DateTime>("SellDate");

                    b.Property<bool>("SelledOrRented");

                    b.Property<int>("TypContract");

                    b.Property<long>("Vadie");

                    b.HasKey("Id");

                    b.HasIndex("AdviserId");

                    b.HasIndex("HomeId");

                    b.ToTable("Contractes");
                });

            modelBuilder.Entity("DomainLayer.CostSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cost");

                    b.Property<long>("CostChance");

                    b.HasKey("Id");

                    b.ToTable("CostSetting");
                });

            modelBuilder.Entity("DomainLayer.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<string>("Birthdate")
                        .IsRequired();

                    b.Property<string>("Code");

                    b.Property<string>("Family")
                        .IsRequired();

                    b.Property<string>("Fathername")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<string>("Number")
                        .IsRequired();

                    b.Property<string>("Sadere")
                        .IsRequired();

                    b.Property<string>("Shenasname")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("DomainLayer.EjareSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cost");

                    b.Property<long>("CostChance");

                    b.HasKey("Id");

                    b.ToTable("EjareSetting");
                });

            modelBuilder.Entity("DomainLayer.Home.Anbar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Arzegozar");

                    b.Property<int>("Arzemelk");

                    b.Property<string>("HomeEmtiaz")
                        .HasMaxLength(1000);

                    b.Property<int>("HomeId");

                    b.Property<int>("MetrazhBena");

                    b.Property<int>("Metrazhzamin");

                    b.Property<string>("MoghiateMelk");

                    b.Property<string>("NegahbaniName")
                        .HasMaxLength(500);

                    b.Property<string>("NegahbaniPhone")
                        .HasMaxLength(500);

                    b.Property<string>("SanadStatus");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Anbars");
                });

            modelBuilder.Entity("DomainLayer.Home.Aparteman", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ghadroalsahm")
                        .HasMaxLength(500);

                    b.Property<string>("HomeEmtiaz")
                        .HasMaxLength(1000);

                    b.Property<string>("HomeFacilities");

                    b.Property<int>("HomeId");

                    b.Property<string>("Homedivar")
                        .HasMaxLength(1000);

                    b.Property<string>("Homejahatevahed")
                        .HasMaxLength(1000);

                    b.Property<string>("Homekaf")
                        .HasMaxLength(1000);

                    b.Property<string>("Homekitchen")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemogheiat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemoshaat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemoshakhase")
                        .HasMaxLength(1000);

                    b.Property<string>("Homenema")
                        .HasMaxLength(1000);

                    b.Property<string>("Homeparking")
                        .HasMaxLength(1000);

                    b.Property<string>("Homesanad")
                        .HasMaxLength(1000);

                    b.Property<string>("Hometasisat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homevaziate")
                        .HasMaxLength(1000);

                    b.Property<string>("Homewc")
                        .HasMaxLength(1000);

                    b.Property<int>("MetrazhBena");

                    b.Property<int>("Metrazhzamin");

                    b.Property<string>("NegahbaniName")
                        .HasMaxLength(500);

                    b.Property<string>("NegahbaniPhone")
                        .HasMaxLength(500);

                    b.Property<int>("Tabaghe");

                    b.Property<int>("Tedadkoltabaghat");

                    b.Property<int>("Tedadkolvahedha");

                    b.Property<int>("Tedadvaheddartabaghe");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Apartemans");
                });

            modelBuilder.Entity("DomainLayer.Home.Edari", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HomeEmtiaz")
                        .HasMaxLength(1000);

                    b.Property<int>("HomeId");

                    b.Property<string>("Homekaf")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemogheiat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homenema")
                        .HasMaxLength(1000);

                    b.Property<string>("Homeparking")
                        .HasMaxLength(1000);

                    b.Property<string>("Homesanad")
                        .HasMaxLength(1000);

                    b.Property<string>("Hometasisat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homevaziate")
                        .HasMaxLength(1000);

                    b.Property<string>("Homewc")
                        .HasMaxLength(1000);

                    b.Property<int>("MetrazhBena");

                    b.Property<string>("NegahbaniName")
                        .HasMaxLength(500);

                    b.Property<string>("NegahbaniPhone")
                        .HasMaxLength(500);

                    b.Property<int>("Tabaghe");

                    b.Property<int>("TedadOtagh");

                    b.Property<int>("Tedadkoltabaghat");

                    b.Property<int>("Tedadkolvahedha");

                    b.Property<int>("Tedadvaheddartabaghe");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Edaries");
                });

            modelBuilder.Entity("DomainLayer.Home.Garden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HomeEmtiaz")
                        .HasMaxLength(1000);

                    b.Property<int>("HomeId");

                    b.Property<int>("Metrazhzamin");

                    b.Property<string>("NegahbaniName")
                        .HasMaxLength(500);

                    b.Property<string>("NegahbaniPhone")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Gardenes");
                });

            modelBuilder.Entity("DomainLayer.Home.GardenWithVila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ghadroalsahm")
                        .HasMaxLength(500);

                    b.Property<string>("HomeEmtiaz")
                        .HasMaxLength(1000);

                    b.Property<int>("HomeId");

                    b.Property<string>("Homedivar")
                        .HasMaxLength(1000);

                    b.Property<string>("Homekaf")
                        .HasMaxLength(1000);

                    b.Property<string>("Homekitchen")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemogheiat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemoshaat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemoshakhase")
                        .HasMaxLength(1000);

                    b.Property<string>("Homenema")
                        .HasMaxLength(1000);

                    b.Property<string>("Homeparking")
                        .HasMaxLength(1000);

                    b.Property<string>("Homesanad")
                        .HasMaxLength(1000);

                    b.Property<string>("Hometasisat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homevaziate")
                        .HasMaxLength(1000);

                    b.Property<string>("Homewc")
                        .HasMaxLength(1000);

                    b.Property<int>("MetrazhBena");

                    b.Property<int>("Metrazhzamin");

                    b.Property<string>("NegahbaniName")
                        .HasMaxLength(500);

                    b.Property<string>("NegahbaniPhone")
                        .HasMaxLength(500);

                    b.Property<int>("Tabaghe");

                    b.Property<int>("TedadOtagh");

                    b.Property<int>("Tedadkoltabaghat");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("gardenWithVilas");
                });

            modelBuilder.Entity("DomainLayer.Home.Home", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int?>("AdvisorId");

                    b.Property<int>("Bana");

                    b.Property<int>("Bath");

                    b.Property<int>("Bed");

                    b.Property<int>("BuildYear");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("Gpsx")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Gpsy")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("HomeMapImage")
                        .HasMaxLength(500);

                    b.Property<int>("Hometype");

                    b.Property<int>("HometypeId");

                    b.Property<string>("Image")
                        .HasMaxLength(1000);

                    b.Property<bool>("IsPrivate");

                    b.Property<bool>("IsShow");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("Parking");

                    b.Property<string>("Phone")
                        .HasMaxLength(100);

                    b.Property<string>("Postalcode")
                        .IsRequired();

                    b.Property<string>("ThreeDView")
                        .HasMaxLength(500);

                    b.Property<string>("Title");

                    b.Property<int>("Usertype");

                    b.HasKey("Id");

                    b.ToTable("Home");
                });

            modelBuilder.Entity("DomainLayer.Home.HomeGallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("HomeId");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("HomeGallery");
                });

            modelBuilder.Entity("DomainLayer.Home.HomewithGarden", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Arzegozar");

                    b.Property<int>("Arzemelk");

                    b.Property<string>("HomeEmtiaz")
                        .HasMaxLength(1000);

                    b.Property<int>("HomeId");

                    b.Property<string>("Homedivar")
                        .HasMaxLength(1000);

                    b.Property<string>("Homekaf")
                        .HasMaxLength(1000);

                    b.Property<string>("Homekitchen")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemogheiat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemoshakhase")
                        .HasMaxLength(1000);

                    b.Property<string>("Homenema")
                        .HasMaxLength(1000);

                    b.Property<string>("Homeparking")
                        .HasMaxLength(1000);

                    b.Property<string>("Homesanad")
                        .HasMaxLength(1000);

                    b.Property<string>("Hometasisat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homevaziate")
                        .HasMaxLength(1000);

                    b.Property<string>("Homewc")
                        .HasMaxLength(1000);

                    b.Property<int>("MetrazhBena");

                    b.Property<int>("Metrazhzamin");

                    b.Property<int>("Tedadkoltabaghat");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("HomewithGardens");
                });

            modelBuilder.Entity("DomainLayer.Home.Kolangi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Arzegozar");

                    b.Property<int>("Arzemelk");

                    b.Property<string>("HomeEmtiaz")
                        .HasMaxLength(1000);

                    b.Property<int>("HomeId");

                    b.Property<string>("Homemogheiat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemoshakhase")
                        .HasMaxLength(1000);

                    b.Property<string>("Homesanad")
                        .HasMaxLength(1000);

                    b.Property<string>("Homevaziate")
                        .HasMaxLength(1000);

                    b.Property<int>("Metrazhbena");

                    b.Property<int>("Metrazhzamin");

                    b.Property<string>("NegahbaniName")
                        .HasMaxLength(500);

                    b.Property<string>("NegahbaniPhone")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Kolangis");
                });

            modelBuilder.Entity("DomainLayer.Home.Maghaze", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DahaneMaghaze");

                    b.Property<string>("HomeEmtiaz")
                        .HasMaxLength(1000);

                    b.Property<int>("HomeId");

                    b.Property<string>("Homedivar")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemogheiat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemoshakhase")
                        .HasMaxLength(1000);

                    b.Property<string>("Homeparking")
                        .HasMaxLength(1000);

                    b.Property<string>("Homesanad")
                        .HasMaxLength(1000);

                    b.Property<string>("Homevaziatemelk")
                        .HasMaxLength(1000);

                    b.Property<string>("Homewc")
                        .HasMaxLength(1000);

                    b.Property<int>("MetrazhKafMaghaze");

                    b.Property<int>("Metrazhanbar");

                    b.Property<int>("Metrazhbalkon");

                    b.Property<string>("NegahbaniName")
                        .HasMaxLength(500);

                    b.Property<string>("NegahbaniPhone")
                        .HasMaxLength(500);

                    b.Property<int>("Tabaghe");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Maghazes");
                });

            modelBuilder.Entity("DomainLayer.Home.Moshtghelat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Arzegozar");

                    b.Property<int>("Arzemelk");

                    b.Property<string>("Ghadroalsahm")
                        .HasMaxLength(500);

                    b.Property<string>("HomeEmtiaz")
                        .HasMaxLength(1000);

                    b.Property<int>("HomeId");

                    b.Property<string>("Homedivar")
                        .HasMaxLength(1000);

                    b.Property<string>("Homekaf")
                        .HasMaxLength(1000);

                    b.Property<string>("Homekitchen")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemogheiat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemoshaat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemoshakhase")
                        .HasMaxLength(1000);

                    b.Property<string>("Homenema")
                        .HasMaxLength(1000);

                    b.Property<string>("Homeparking")
                        .HasMaxLength(1000);

                    b.Property<string>("Homesanad")
                        .HasMaxLength(1000);

                    b.Property<string>("Hometasisat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homevaziate")
                        .HasMaxLength(1000);

                    b.Property<string>("Homewc")
                        .HasMaxLength(1000);

                    b.Property<int>("MetrazhBena");

                    b.Property<int>("Metrazhzamin");

                    b.Property<string>("NegahbaniName")
                        .HasMaxLength(500);

                    b.Property<string>("NegahbaniPhone")
                        .HasMaxLength(500);

                    b.Property<int>("Tabaghe");

                    b.Property<int>("Tedadkoltabaghat");

                    b.Property<int>("Tedadkolvahedha");

                    b.Property<int>("Tedadvaheddartabaghe");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Moshtghelats");
                });

            modelBuilder.Entity("DomainLayer.Home.Vila", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HomeEmtiaz")
                        .HasMaxLength(1000);

                    b.Property<int>("HomeId");

                    b.Property<string>("Homedivar")
                        .HasMaxLength(1000);

                    b.Property<string>("Homekaf")
                        .HasMaxLength(1000);

                    b.Property<string>("Homekitchen")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemogheiat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemoshaat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homemoshakhase")
                        .HasMaxLength(1000);

                    b.Property<string>("Homenema")
                        .HasMaxLength(1000);

                    b.Property<string>("Homeparking")
                        .HasMaxLength(1000);

                    b.Property<string>("Homesanad")
                        .HasMaxLength(1000);

                    b.Property<string>("Hometasisat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homevaziate")
                        .HasMaxLength(1000);

                    b.Property<string>("Homewc")
                        .HasMaxLength(1000);

                    b.Property<int>("MetrazhBena");

                    b.Property<int>("Metrazhzamin");

                    b.Property<string>("NegahbaniName")
                        .HasMaxLength(500);

                    b.Property<string>("NegahbaniPhone")
                        .HasMaxLength(500);

                    b.Property<int>("Tedadkoltabaghat");

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Vilas");
                });

            modelBuilder.Entity("DomainLayer.Home.Zamin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Arzegozar");

                    b.Property<int>("Arzemelk");

                    b.Property<string>("HomeEmtiaz")
                        .HasMaxLength(1000);

                    b.Property<int>("HomeId");

                    b.Property<string>("Homemogheiat")
                        .HasMaxLength(1000);

                    b.Property<string>("Homesanad")
                        .HasMaxLength(1000);

                    b.Property<string>("Homevaziate")
                        .HasMaxLength(1000);

                    b.Property<int>("Metrazhzamin");

                    b.Property<string>("NegahbaniName")
                        .HasMaxLength(500);

                    b.Property<string>("NegahbaniPhone")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.HasIndex("HomeId");

                    b.ToTable("Zamins");
                });

            modelBuilder.Entity("DomainLayer.HomeFacility", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon")
                        .HasMaxLength(500);

                    b.Property<int>("MelkType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<bool>("Selected");

                    b.Property<bool>("ShowinSearch");

                    b.Property<int>("TypeHome");

                    b.HasKey("Id");

                    b.ToTable("HomeFacility");
                });

            modelBuilder.Entity("DomainLayer.HomeGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon")
                        .HasMaxLength(500);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("HomeGroup");
                });

            modelBuilder.Entity("DomainLayer.Location.Mahalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Gpsx")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Gpsy")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("NahieId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("NahieId");

                    b.ToTable("Mahale");
                });

            modelBuilder.Entity("DomainLayer.Location.Nahie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CityId");

                    b.Property<string>("Gpsx")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Gpsy")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(1000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Nahie");
                });

            modelBuilder.Entity("DomainLayer.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LogController")
                        .IsRequired();

                    b.Property<string>("LogText")
                        .IsRequired();

                    b.Property<string>("LogView")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("DomainLayer.Magzine.Magazine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date");

                    b.Property<string>("Image")
                        .HasMaxLength(500);

                    b.Property<int>("MagazinGroupId");

                    b.Property<string>("Tags")
                        .HasMaxLength(500);

                    b.Property<string>("Text")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("UrlTour360")
                        .HasMaxLength(500);

                    b.Property<int>("ViewerCount");

                    b.HasKey("Id");

                    b.HasIndex("MagazinGroupId");

                    b.ToTable("Magazin");
                });

            modelBuilder.Entity("DomainLayer.Magzine.MagazinGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasMaxLength(50);

                    b.Property<int?>("ParentId");

                    b.HasKey("Id");

                    b.ToTable("MagazinGroup");
                });

            modelBuilder.Entity("DomainLayer.MetrazSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Metraz");

                    b.Property<int>("MetrazChance");

                    b.Property<int>("TypeMetraz");

                    b.HasKey("Id");

                    b.ToTable("MetrazSetting");
                });

            modelBuilder.Entity("DomainLayer.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Gpsx")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Gpsy")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Region");
                });

            modelBuilder.Entity("DomainLayer.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aparat")
                        .HasMaxLength(500);

                    b.Property<string>("Author")
                        .HasMaxLength(500);

                    b.Property<string>("Description")
                        .HasMaxLength(1000);

                    b.Property<string>("Googleplus")
                        .HasMaxLength(500);

                    b.Property<string>("Icon")
                        .HasMaxLength(500);

                    b.Property<string>("Instagram")
                        .HasMaxLength(500);

                    b.Property<string>("Keys")
                        .HasMaxLength(1000);

                    b.Property<string>("Mobile")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .HasMaxLength(100);

                    b.Property<string>("Telegram")
                        .HasMaxLength(500);

                    b.Property<string>("Title")
                        .HasMaxLength(500);

                    b.Property<string>("Twitter")
                        .HasMaxLength(500);

                    b.Property<string>("Youtube")
                        .HasMaxLength(500);

                    b.HasKey("Id");

                    b.ToTable("Setting");
                });

            modelBuilder.Entity("DomainLayer.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active");

                    b.Property<string>("Activecode")
                        .HasMaxLength(20);

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("DomainLayer.VadieSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cost");

                    b.Property<long>("CostChance");

                    b.HasKey("Id");

                    b.ToTable("VadieSetting");
                });

            modelBuilder.Entity("DomainLayer.City", b =>
                {
                    b.HasOne("DomainLayer.Region", "Region")
                        .WithMany("Cities")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Contract.Contract", b =>
                {
                    b.HasOne("DomainLayer.Adviser", "Adviser")
                        .WithMany("Contracts")
                        .HasForeignKey("AdviserId");

                    b.HasOne("DomainLayer.Home.Home", "Home")
                        .WithMany("Contracts")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Home.Anbar", b =>
                {
                    b.HasOne("DomainLayer.Home.Home", "Home")
                        .WithMany("Anbar")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Home.Aparteman", b =>
                {
                    b.HasOne("DomainLayer.Home.Home", "Home")
                        .WithMany("Aparteman")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Home.Edari", b =>
                {
                    b.HasOne("DomainLayer.Home.Home", "Home")
                        .WithMany("Edari")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Home.Garden", b =>
                {
                    b.HasOne("DomainLayer.Home.Home", "Home")
                        .WithMany("Garden")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Home.GardenWithVila", b =>
                {
                    b.HasOne("DomainLayer.Home.Home", "Home")
                        .WithMany("GardenWithVila")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Home.HomeGallery", b =>
                {
                    b.HasOne("DomainLayer.Home.Home", "Home")
                        .WithMany("HomeGalleries")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Home.HomewithGarden", b =>
                {
                    b.HasOne("DomainLayer.Home.Home", "Home")
                        .WithMany("HomewithGarden")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Home.Kolangi", b =>
                {
                    b.HasOne("DomainLayer.Home.Home", "Home")
                        .WithMany("Kolangi")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Home.Maghaze", b =>
                {
                    b.HasOne("DomainLayer.Home.Home", "Home")
                        .WithMany("Maghaze")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Home.Moshtghelat", b =>
                {
                    b.HasOne("DomainLayer.Home.Home", "Home")
                        .WithMany("Moshtghelat")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Home.Vila", b =>
                {
                    b.HasOne("DomainLayer.Home.Home", "Home")
                        .WithMany("Vila")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Home.Zamin", b =>
                {
                    b.HasOne("DomainLayer.Home.Home", "Home")
                        .WithMany("Zamin")
                        .HasForeignKey("HomeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Location.Mahalle", b =>
                {
                    b.HasOne("DomainLayer.Location.Nahie", "Nahie")
                        .WithMany("Mahalles")
                        .HasForeignKey("NahieId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Location.Nahie", b =>
                {
                    b.HasOne("DomainLayer.City", "City")
                        .WithMany("Nahies")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("DomainLayer.Magzine.Magazine", b =>
                {
                    b.HasOne("DomainLayer.Magzine.MagazinGroup", "MagazinGroup")
                        .WithMany("Magazines")
                        .HasForeignKey("MagazinGroupId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
